server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Animes API Developed by Breno Martins during the Springboot essentials course by DevDojo
  github: https://github.com/martnsBreno/Springboot-Essentials